Repository nodejs/nodejs.org, pull requests merged in 2018-07, with the labels that each got.

#1722 [Fix] Fix styles of `hbs` files
  layouts/partials/header.hbs
  layouts/partials/navigation.hbs
Labels: bug

#1726 sync locale/uk/index.md with the original
  locale/uk/index.md
Labels: content, i18n

#1719 [Fix] Remove duplicated Translations for `index.md` with unnecessary double quotes
  locale/zh-cn/index.md
Labels: on hold/needs i18n +1

#1721 [Localization] Translate For `local\zh-CN\about`
  locale/zh-cn/about/community.md
  locale/zh-cn/about/governance.md
  locale/zh-cn/about/index.md
  locale/zh-cn/about/privacy.md
  locale/zh-cn/about/releases.md
  locale/zh-cn/about/resources.md
  locale/zh-cn/about/trademark.md
  locale/zh-cn/about/working-groups.md
Labels: on hold/needs i18n +1
