Repository nodejs/nodejs.org, pull requests merged in 2018-12, with the labels that each got.

#1920 Update blocking-vs-non-blocking.md
  locale/zh-cn/docs/guides/blocking-vs-non-blocking.md
Labels: on hold/needs i18n +1

#1918 Add Korean translation
  locale/ko/docs/guides/getting-started-guide.md
  locale/ko/docs/guides/index.md
Labels: i18n, on hold/needs i18n +1

#1928 zh-cn: translate guide for consistency
  locale/zh-cn/docs/guides/debugging-getting-started.md
  locale/zh-cn/docs/guides/getting-started-guide.md
  locale/zh-cn/docs/guides/index.md
  locale/zh-cn/site.json
Labels: i18n, on hold/needs i18n +1

#1951 zh-CN：Trans for Gitpod
  locale/zh-cn/docs/guides/debugging-getting-started.md
Labels: i18n

#1947 nodejs-pt-br: Add files & Translate to brazilian portuguese - '404.md…
  locale/pt-br/404.md
  locale/pt-br/index.md
  locale/pt-br/site.json
Labels: i18n

#1913 Update built-in debugger link to latest
  locale/ko/docs/guides/debugging-getting-started.md
Labels: content

#1955 Translate get involved to pt-br
  locale/pt-br/get-involved/code-and-learn.md
  locale/pt-br/get-involved/collab-summit.md
  locale/pt-br/get-involved/contribute.md
  locale/pt-br/get-involved/index.md
Labels: on hold/needs i18n +1

#1958 zh-cn: simplify/clarify first paragraph of security.md
  locale/zh-cn/security.md
Labels: i18n

#1929 update korean translation
  locale/ko/docs/guides/debugging-getting-started.md
  locale/ko/docs/inspector.md
  locale/ko/site.json
Labels: i18n, on hold/needs i18n +1
