Repository nodejs/nodejs.org, pull requests merged in 2019-02, with the labels that each got.

#1979 Korean translation for package-manager.md
  locale/ko/download/package-manager.md
Labels: i18n, on hold/needs i18n +1

#1994 doc: update info about Node.js installation on Android via Termux
  locale/en/download/package-manager.md
  locale/es/download/package-manager.md
  locale/fa/download/package-manager.md
  locale/ja/download/package-manager.md
  locale/ko/download/package-manager.md
  locale/uk/download/package-manager.md
  locale/zh-cn/download/package-manager.md
  locale/zh-tw/download/package-manager.md
Labels: on hold/needs i18n +1

#1762 Italian translations
  locale/it/404.md
  locale/it/about/community.md
  locale/it/about/governance.md
  locale/it/about/index.md
  locale/it/about/resources.md
  locale/it/about/trademark.md
  locale/it/about/working-groups.md
  locale/it/docs/es6.md
  locale/it/docs/guides/anatomy-of-an-http-transaction.md
  locale/it/docs/guides/backpressuring-in-streams.md
  locale/it/docs/guides/blocking-vs-non-blocking.md
  locale/it/docs/guides/buffer-constructor-deprecation.md
  locale/it/docs/guides/debugging-getting-started.md
  locale/it/docs/guides/domain-postmortem.md
  locale/it/docs/guides/dont-block-the-event-loop.md
  locale/it/docs/guides/event-loop-timers-and-nexttick.md
  locale/it/docs/guides/getting-started-guide.md
  locale/it/docs/guides/index.md
  locale/it/docs/guides/nodejs-docker-webapp.md
  locale/it/docs/guides/publishing-napi-modules.md
  locale/it/docs/guides/simple-profiling.md
  locale/it/docs/guides/timers-in-node.md
  locale/it/docs/guides/working-with-different-filesystems.md
  locale/it/docs/index.md
  locale/it/docs/meta/topics/dependencies.md
  locale/it/download/current.md
  locale/it/download/index.md
  locale/it/download/package-manager.md
  locale/it/download/releases.md
  locale/it/get-involved/collab-summit.md
  locale/it/get-involved/contribute.md
  locale/it/get-involved/index.md
  locale/it/security.md
  locale/it/site.json
Labels: i18n, on hold/needs i18n +1

#1938 Re-added NiM link to documentation. Also 25 language additions to debugging documentation.
  locale/en/docs/guides/debugging-getting-started.md
  locale/fa/docs/guides/debugging-getting-started.md
  locale/ja/docs/guides/debugging-getting-started.md
  locale/ko/docs/guides/debugging-getting-started.md
  locale/zh-cn/docs/guides/debugging-getting-started.md
  scripts/contributor-list/index.js
Labels: on hold/needs i18n +1

#1444 Add first of the new diagnostics articles to guides
  locale/en/docs/guides/diagnostics-flamegraph.md
Labels: external/docs, help wanted, on hold/needs original poster

#2024 translate about page in italian
  locale/it/about/index.md
  locale/it/about/resources.md
Labels: on hold/needs i18n +1

#2100 Update file get-involved/index.md AR
  locale/ar/get-involved/index.md
Labels: i18n
