Repository nodejs/nodejs.org, pull requests merged in 2019-08, with the labels that each got.

#2349 AR : Fix the style / structure of download section ..
  locale/ar/download/current.md
  locale/ar/download/index.md
  locale/ar/download/package-manager.md
  locale/ar/download/releases.md
Labels: i18n

#2356 JA : Translate middle of "setImmediate"
  locale/ja/docs/guides/timers-in-node.md
Labels: i18n

#2359 KO : Update index.md
  locale/ko/docs/index.md
Labels: i18n

#2337 RU: blocking vs non-blocking guide
  locale/ru/docs/guides/blocking-vs-non-blocking.md
  locale/ru/docs/guides/index.md
Labels: i18n

#2318 PT-BR : Add file what-is-the-arguments-object.md
  locale/pt-br/knowledge/javascript-conventions/what-is-the-arguments-object.md
Labels: i18n

#2431 AR: add translation of dependencies.md ..
  locale/ar/docs/meta/topics/dependencies.md
Labels: i18n

#2456 AR: fix node-meetups page ..
  locale/ar/get-involved/node-meetups.md
Labels: i18n

#2310 [pt-br] 5.8 file-system
  locale/pt-br/knowledge/file-system/how-to-read-files-in-nodejs.md
  locale/pt-br/knowledge/file-system/how-to-search-files-and-directories-in-nodejs.md
  locale/pt-br/knowledge/file-system/how-to-store-local-config-data.md
  locale/pt-br/knowledge/file-system/how-to-use-the-path-module.md
  locale/pt-br/knowledge/file-system/how-to-write-files-in-nodejs.md
  locale/pt-br/knowledge/file-system/security/introduction.md
Labels: i18n, on hold

#2457 fixture: watch cannot build when files are changed or added successfully
  build.js
  server.js
Labels: bug
