Repository nodejs/nodejs.org, pull requests merged in 2023-04, with the labels that each got.

#5214 chore: set up storybook (#5191)
  .eslintrc
  .storybook/constants.ts
  .storybook/main.js
  .storybook/preview.js
  CONTRIBUTING.md
  components/Footer.stories.ts
  components/Header.stories.ts
  package-lock.json
  package.json
Labels: website redesign

#5213 chore(build): use workers for less intensive memory usage
  next.config.mjs
  package-lock.json
Labels: fast-track

#5217 docs: extended security guide to include OpenSSF tooling
  pages/en/docs/guides/security/index.md
Labels: fast-track

#5233 📎 chore(migration): migrate banner component
  components/Common/Banner/Banner.stories.tsx
  components/Common/Banner/__tests__/index.test.tsx
  components/Common/Banner/index.module.scss
  components/Common/Banner/index.tsx
  i18n/locales/ca.json
  i18n/locales/en.json
  util/isAbsoluteUrl.ts
Labels: website redesign

#5238 feat: migrate AnimatedPlaceholder component (#5238
  components/Common/AnimatedPlaceholder/AnimatedPlaceholder.stories.tsx
  components/Common/AnimatedPlaceholder/__tests__/__snapshots__/index.test.tsx.snap
  components/Common/AnimatedPlaceholder/__tests__/index.test.tsx
  components/Common/AnimatedPlaceholder/index.module.scss
  components/Common/AnimatedPlaceholder/index.tsx
Labels: website redesign

#5243 feat: create article alert component
  components/Article/Alert/__tests__/__snapshots__/index.test.tsx.snap
  components/Article/Alert/__tests__/index.test.tsx
  components/Article/Alert/index.module.scss
  components/Article/Alert/index.stories.ts
  components/Article/Alert/index.tsx
Labels: website redesign

#5258 chore: call Prettier as part of lint CI
  .prettierignore
  i18n/locales/ca.json
  package.json
Labels: fast-track

#5263 blog: add windows arm64 for v19.9.0 and later
  pages/en/blog/release/v19.9.0.md
  scripts/release-post/downloadsTable.mjs
Labels: fast-track

#5274 fix: other downloads incorrect for 'current'
  components/Home/HomeDownloadButton.tsx
Labels: fast-track

#5281 feat(stylelint,storybook): fixed styleling misconfig and fixed storybooks
  .storybook/constants.js
  .storybook/main.ts
  .storybook/preview.tsx
  .stylelintrc
  components/Common/Banner/Banner.stories.tsx
  components/Common/Banner/index.module.scss
  package-lock.json
  package.json
Labels: fast-track

#5292 Blog: fix banner link and announce post for Node.js 20
  pages/en/blog/announcements/v20-release-announce.md
  site.json
Labels: fast-track

#5277 feat: migrate AuthorList component and add story 🎉
  components/Article/AuthorList/Author/__tests__/__snapshots__/index.test.tsx.snap
  components/Article/AuthorList/Author/__tests__/index.test.tsx
  components/Article/AuthorList/Author/index.module.scss
  components/Article/AuthorList/Author/index.tsx
  components/Article/AuthorList/__tests__/__snapshots__/authors-list.test.tsx.snap
  components/Article/AuthorList/__tests__/authors-list.test.tsx
  components/Article/AuthorList/index.module.scss
  components/Article/AuthorList/index.stories.tsx
  components/Article/AuthorList/index.tsx
  i18n/locales/en.json
  public/placeholder-img.png
Labels: website redesign

#5236 feat(DarkModeToggler): Migrate and add stories to theme toggler 🎉
  .storybook/preview.tsx
  .stylelintignore
  components/Common/DarkModeToggle/__tests__/__snapshots__/index.test.tsx.snap
  components/Common/DarkModeToggle/__tests__/index.test.tsx
  components/Common/DarkModeToggle/index.module.scss
  components/Common/DarkModeToggle/index.stories.tsx
  components/Common/DarkModeToggle/index.tsx
  package-lock.json
  package.json
  styles/_base.scss
  styles/layout/_dark-theme.scss
  styles/tokens.scss
Labels: website redesign

#5319 chore: fix storybook styles, imports, typescript config and dependencies (#5319
  .storybook/constants.js
  .storybook/constants.ts
  .storybook/preview.tsx
  components/Common/AnimatedPlaceholder/index.stories.tsx
  components/Common/Banner/index.module.scss
  components/Common/Banner/index.stories.tsx
  components/Common/DarkModeToggle/__tests__/__snapshots__/index.test.tsx.snap
  components/Common/DarkModeToggle/__tests__/index.test.tsx
  components/Common/DarkModeToggle/index.tsx
  components/Common/LanguageSelector/__tests__/index.test.tsx
  components/Common/LanguageSelector/index.tsx
  global.d.ts
  i18n/locales/en.json
  jsconfig.json
  package-lock.json
  package.json
  pages/_app.mdx
  styles/base.scss
  styles/index.scss
  styles/old/_base.scss
  styles/old/_utils.scss
  styles/old/_variables.scss
  styles/old/index.scss
  styles/old/layout/_dark-theme.scss
  styles/old/layout/_grid.scss
  styles/old/layout/_lists.scss
  styles/old/layout/_main.scss
  styles/old/layout/_sticky-footer.scss
  styles/old/page-modules/_anchorLinks.scss
  styles/old/page-modules/_blog-index.scss
  styles/old/page-modules/_blog-post.scss
  styles/old/page-modules/_download.scss
  styles/old/page-modules/_footer.scss
  styles/old/page-modules/_header.scss
  styles/old/page-modules/_home.scss
  styles/old/page-modules/_jsfoundation.scss
  styles/old/page-modules/_prev-next-navigation.scss
  styles/old/page-modules/_scrollToTop.scss
  styles/old/vendor/prism-tomorrow.css
  tsconfig.json
  util/openSans.ts
Labels: fast-track, website redesign

#5316 chore: adopt turborepo (#5316
  .browserslistrc
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/github-pages.yml
  .github/workflows/pull-request.yml
  .gitignore
  .storybook/main.ts
  .stylelintignore
  CONTRIBUTING.md
  README.md
  jest.config.mjs
  jest.setup.mjs
  next.data.mjs
  package-lock.json
  package.json
  turbo.json
Labels: fast-track, website redesign

#5323 feat(blog) Migrate BlogCard component
  components/Blog/BlogCard/__tests__/__snapshots__/index.test.tsx.snap
  components/Blog/BlogCard/__tests__/index.test.tsx
  components/Blog/BlogCard/index.module.scss
  components/Blog/BlogCard/index.stories.tsx
  components/Blog/BlogCard/index.tsx
  i18n/locales/en.json
  types/blog.ts
Labels: website redesign

#5326 chore: add remote turbo cache and simplified gh actions cache (#5326)Co-authored-by: Aymen Naghmouchi <aymenadvance@gmail.com>
  .github/workflows/github-pages.yml
  .github/workflows/pull-request.yml
Labels: infrastructure
