Repository nodejs/nodejs.org, pull requests merged in 2023-06, with the labels that each got.

#5415 id, zh-CN: new and update translations
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: i18n, crowdin

#5423 id,zh-CN: update translations
  pages/id/docs/guides/nodejs-docker-webapp.md
  pages/zh-cn/docs/guides/nodejs-docker-webapp.md
  pages/zh-cn/download/package-manager.md
  pages/zh-cn/get-involved/collab-summit.md
Labels: i18n, crowdin

#5424 id, zh-CN: localize some files
  i18n/locales/id.json
  i18n/locales/zh-cn.json
  pages/id/docs/guides/nodejs-docker-webapp.md
Labels: i18n, crowdin

#5437 chore: reduce requirement from 2 approvals to 1
  CONTRIBUTING.md
Labels: meta

#5441 chore: update process to become a collaborator
  CONTRIBUTING.md
Labels: meta

#5449 Chore: remove obsolete package repository
  pages/en/download/package-manager.md
  pages/id/download/package-manager.md
  pages/nl/download/package-manager.md
Labels: fast-track

#5450 zh-CN: update translations
  pages/ko/docs/guides/diagnostics/memory/index.md
  pages/ko/docs/index.mdx
  pages/zh-cn/docs/meta/topics/dependencies.md
  pages/zh-cn/download/package-manager.md
Labels: i18n, crowdin

#5459 feat: ssr sitemap
  app/en/feed/[feed]/route.ts
  app/sitemap.xml/route.ts
  next-sitemap.config.mjs
  package.json
Labels: website redesign, infrastructure
