Repository nodejs/nodejs.org, pull requests merged in 2023-11, with the labels that each got.

#6090 Add shas to workflow images
  .github/workflows/build.yml
  .github/workflows/lint-and-tests.yml
  .github/workflows/pull-request-label.yml
  .github/workflows/translations-pr.yml
Labels: fast-track

#6095 meta: correct attribution in v20.6.0 release notes
  pages/en/blog/release/v20.6.0.md
Labels: fast-track

#6103 fix: use html links when needed
  components/Common/ActiveLocalizedLink/index.tsx
  components/Common/Badge/index.tsx
  components/Common/Banner/index.tsx
  components/Common/Breadcrumbs/BreadcrumbLink/index.tsx
  components/Common/CrossLink/index.tsx
  components/Common/MetaBar/index.stories.tsx
  components/Common/MetaBar/index.tsx
  components/Common/Pagination/PaginationListItem/index.tsx
  components/Downloads/DownloadList.tsx
  components/Downloads/PrimaryDownloadMatrix.tsx
  components/Footer.tsx
  components/Header.tsx
  components/Home/HomeDownloadButton.tsx
  components/Link.tsx
  components/Pagination.tsx
  components/SideNavigation.tsx
  layouts/BlogCategoryLayout.tsx
  next.mdx.use.mjs
Labels: bug, infrastructure

#6113 fix: Blog pagination / Blog category listing
  components/withLayout.tsx
  hooks/useBaseBlogData.ts
  pages/en/blog/advisory-board/index.md
  pages/en/blog/announcements/index.md
  pages/en/blog/community/index.md
  pages/en/blog/feature/index.md
  pages/en/blog/index.md
  pages/en/blog/module/index.md
  pages/en/blog/npm/index.md
  pages/en/blog/pagination.md
  pages/en/blog/release/index.md
  pages/en/blog/uncategorized/index.md
  pages/en/blog/video/index.md
  pages/en/blog/vulnerability/index.md
  pages/en/blog/weekly-updates/index.md
  types/layouts.ts
Labels: fast-track

#6072 feat: Added Navbar component
  components/Common/LanguageDropDown/index.stories.tsx
  components/Common/LanguageDropDown/index.tsx
  components/Containers/NavigationBar/index.module.css
  components/Containers/NavigationBar/index.stories.tsx
  components/Containers/NavigationBar/index.tsx
  components/Icons/GitHubLogo.tsx
  components/Icons/NodejsLogoDark.tsx
  components/Icons/NodejsLogoLight.tsx
  package-lock.json
  package.json
Labels: hacktoberfest

#6120 refactor: remove unnecessary hook
  components/Common/ActiveLink/__tests__/index.test.mjs
  components/Common/ActiveLink/index.tsx
  components/Containers/NavItem/index.tsx
  components/Header.tsx
  components/SideNavigation.tsx
  hooks/react-client/index.ts
  hooks/react-client/useIsCurrentPathname.ts
  hooks/react-server/index.ts
  hooks/react-server/useIsCurrentPathname.ts
  layouts/DocsLayout.tsx
  styles/old/index.css
  styles/old/layout/dark-theme.css
  styles/old/page-modules/header.css
  util/getBitness.ts
Labels: fast-track

#6121 tune sentry collection rates per docs
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: fast-track

#6128 refactor: lazy-load sentry
  next.config.mjs
  next.constants.mjs
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: infrastructure

#6130 meta: updated next-intl and dependent packages
  i18n.tsx
  layouts/DocsLayout.tsx
  package-lock.json
  package.json
Labels: i18n, infrastructure

#6134 fix: locale and layouts errors
  .github/workflows/build.yml
  app/[locale]/layout.tsx
  app/[locale]/not-found.tsx
  app/not-found.tsx
Labels: fast-track, infrastructure

#6133 feat: enable sentry features
  app/[locale]/error.tsx
  app/[locale]/layout.tsx
  components/withNodeRelease.tsx
  layouts/BaseLayout.tsx
  next-data/generateNodeReleasesJson.mjs
  next.config.mjs
  next.constants.mjs
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: infrastructure

#6141 Add SPDX identifier to LICENSE
  LICENSE
Labels: fast-track

#6146 fix: make headers on the website bold
  styles/old/base.css
Labels: fast-track

#6144 fix: fixes sentry errors on 404's pages
  .storybook/main.ts
  app/[locale]/layout.tsx
  app/[locale]/not-found.tsx
  next.config.mjs
  package-lock.json
  package.json
  sentry.edge.config.ts
  sentry.server.config.ts
Labels: bug, infrastructure
