Repository nodejs/nodejs.org, pull requests merged in 2023-09, with the labels that each got.

#5733 chore: remove banner component
  components/Common/Banner/__tests__/index.test.mjs
  components/Common/Banner/index.module.scss
  components/Common/Banner/index.stories.tsx
  components/Common/Banner/index.tsx
  i18n/locales/en.json
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: fast-track

#5731 chore(i18n): crowdin sync
  pages/ko/docs/guides/diagnostics/live-debugging/using-inspector.md
Labels: i18n, crowdin

#5757 chore(i18n): crowdin sync
  pages/id/docs/index.mdx
  pages/uk/docs/index.mdx
  pages/zh-cn/docs/index.mdx
Labels: i18n, crowdin

#5782 chore(i18n): crowdin sync
  pages/be/download/releases.md
Labels: i18n, crowdin

#5806 meta: remove remark-gfm (and update dependabot)
  .github/dependabot.yml
  .github/workflows/build.yml
  COLLABORATOR_GUIDE.md
  next.dynamic.mjs
  package-lock.json
  package.json
Labels: fast-track

#5803 chore(i18n): crowdin sync
  pages/be/download/releases.md
Labels: i18n, crowdin

#5812 meta: update next.js and remove robots.txt gen
  .gitignore
  app/robots.ts
  app/sitemap.ts
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  robots.config.mjs
Labels: fast-track, infrastructure

#5875 meta: separate constants and introduce extra classes per theme
  .storybook/constants.ts
  .storybook/preview.tsx
  tailwind.config.ts
Labels: fast-track

#5888 feat: switch from scss to postcss
  .gitignore
  .lintstagedrc.json
  .prettierrc.json
  .storybook/constants.ts
  .storybook/main.ts
  .storybook/preview-body.html
  .storybook/preview.tsx
  .stylelintrc.mjs
  .vscode/extensions.json
  .vscode/settings.json
  COLLABORATOR_GUIDE.md
  components/Common/Badge/index.module.css
  components/Common/Badge/index.tsx
  components/Common/Banner/index.module.css
  components/Common/Banner/index.tsx
  layouts/AboutLayout.tsx
  layouts/ContributeLayout.tsx
  layouts/DocsLayout.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  postcss.config.js
  styles/mixins/_components.scss
  styles/mixins/_screen.scss
  styles/new/index.css
  styles/new/index.scss
  styles/old/base.css
  styles/old/index.css
  styles/old/layout/dark-theme.css
  styles/old/layout/grid.css
  styles/old/layout/lists.css
  styles/old/layout/main.css
  styles/old/layout/sticky-footer.css
  styles/old/page-modules/anchorLinks.css
  styles/old/page-modules/blog-index.css
  styles/old/page-modules/blog-post.css
  styles/old/page-modules/download.css
  styles/old/page-modules/footer.css
  styles/old/page-modules/header.css
  styles/old/page-modules/home.css
  styles/old/page-modules/jsfoundation.css
  styles/old/page-modules/prev-next-navigation.css
  styles/old/page-modules/scrollToTop.css
  styles/old/utils.css
  styles/old/variables.css
  tailwind.config.ts
  tsconfig.json
  turbo.json
Labels: design, website redesign, infrastructure

#5890 Hex logos
  components/__design__/hex-logos.stories.tsx
  public/static/images/logos/hex-black.svg
  public/static/images/logos/hex-green.svg
Labels: fast-track

#5902 chore(i18n): crowdin sync
  .github/workflows/translations-pr.yml
  i18n/locales/fr.json
  pages/fr/about/governance.md
  pages/zh-cn/docs/guides/backpressuring-in-streams.md
  pages/zh-cn/docs/index.mdx
Labels: i18n
