Repository nodejs/nodejs.org, pull requests merged in 2023-07, with the labels that each got.

#5455 chore: check code format on ci
  .github/workflows/pull-request.yml
  .husky/pre-commit
  pages/ko/docs/index.mdx
  public/blog-posts-data.json
Labels: github_actions

#5464 feat: provided some file structural changes
  .husky/pre-commit
  .storybook/test-runner.ts
  app/en/feed/[feed]/route.ts
  components/Article/Codebox/__tests__/index.test.tsx
  components/Article/Codebox/index.tsx
  components/Common/Banner/__snapshots__/index.stories.tsx.snap
  components/Common/Banner/__tests__/index.test.tsx
  components/Common/Banner/index.tsx
  layouts/DownloadReleasesLayout.tsx
  next-data/generateBlogPostsData.mjs
  next-data/index.mjs
  next.config.mjs
  next.data.mjs
  next.dynamic.mjs
  next.helpers.mjs
  package-lock.json
  package.json
  providers/mdxProvider.tsx
  scripts/prebuild/generateNextData.mjs
  scripts/release-post/index.mjs
  theme.tsx
Labels: fast-track

#5468 chore: remove github pages
  .github/workflows/github-pages.yml
  README.md
Labels: fast-track

#5469 feat: created theme provider and remove next.app.mjs
  .storybook/main.ts
  .storybook/preview.tsx
  next.app.tsx
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  providers/themeProvider.tsx
Labels: website redesign, infrastructure

#5467 feat: better separation of mdx content and headings support
  next.config.mjs
  next.dynamic.mjs
  package-lock.json
  package.json
  pages/[...path].tsx
  providers/mdxProvider.tsx
  theme.tsx
  types/dynamic.ts
  types/index.ts
Labels: website redesign, feature-request, infrastructure

#5474 fix: fixed localized links and next links redirection
  .eslintrc
  components/Common/ActiveLocalizedLink/index.tsx
  components/Downloads/DownloadReleasesTable.tsx
  components/Downloads/DownloadToggle/index.module.scss
  components/Home/Banner.tsx
  components/Home/HomeDownloadButton.tsx
  components/Learn/PreviousNextLink/__snapshots__/index.stories.tsx.snap
  components/Learn/PreviousNextLink/__tests__/index.test.tsx
  components/Learn/PreviousNextLink/index.tsx
  components/LocalizedLink.tsx
  components/Sections/NewHeader/__snapshots__/index.stories.tsx.snap
  components/Sections/NewHeader/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
Labels: bug, fast-track, infrastructure

#5475 chore: new constants and better analytics
  app/sitemap.xml/route.ts
  components/HtmlHead.tsx
  next-data/generateWebsiteFeeds.mjs
  next.constants.mjs
  pages/_app.tsx
Labels: bug, fast-track, infrastructure

#5479 fix: use proper datetime to fix server-side/client-siode mismatch
  layouts/BlogIndexLayout.tsx
  layouts/BlogPostLayout.tsx
  layouts/CategoryIndexLayout.tsx
  next-data/generateBlogPostsData.mjs
  package-lock.json
  package.json
  theme.tsx
  util/formatTime.ts
  util/getTimeComponent.tsx
Labels: bug, fast-track, infrastructure

#5494 chore: use defined urls for distribution and api docs
  components/Api/JsonLink/index.tsx
  components/Docs/NodeApiVersionLinks.tsx
  components/Downloads/PrimaryDownloadMatrix.tsx
  components/Downloads/SecondaryDownloadMatrix.tsx
  components/Home/HomeDownloadButton.tsx
  next.constants.mjs
  util/downloadUrlByOS.ts
  util/getNodeApiLink.ts
Labels: fast-track, infrastructure

#5489 chore: attempt to create a bundle analysis file
  .github/workflows/pull-request.yml
Labels: github_actions, fast-track

#5493 chore: added dependabot for npm
  .github/dependabot.yml
Labels: infrastructure

#5495 fix(config): call eslint and prettier directly
  .lintstagedrc
Labels: fast-track

#5499 id,zh-CN: update translations
  pages/id/docs/index.mdx
  pages/zh-cn/docs/index.mdx
Labels: i18n, crowdin

#5425 chore: merge shellbox into codebox
  components/Article/Codebox/__snapshots__/index.stories.tsx.snap
  components/Article/Codebox/__tests__/__snapshots__/index.test.tsx.snap
  components/Article/Codebox/__tests__/index.test.tsx
  components/Article/Codebox/index.module.scss
  components/Article/Codebox/index.stories.tsx
  components/Article/Codebox/index.tsx
  components/Article/Codebox/themes/_light.scss
  components/Article/InlineCode/index.module.scss
  components/Common/ShellBox/__snapshots__/index.stories.tsx.snap
  components/Common/ShellBox/__tests__/index.test.tsx
  components/Common/ShellBox/index.module.scss
  components/Common/ShellBox/index.stories.tsx
  components/Common/ShellBox/index.tsx
  hooks/usePrismJS.ts
  i18n/locales/en.json
  next.prism.mjs
  styles/_tokens.scss
  styles/mixins/_components.scss
  util/nextFonts.ts
Labels: website redesign, feature-request

#5514 chore: renamed .rc files to proper .json extension
  .eslintrc.json
  .gitignore
  .lintstagedrc
  .lintstagedrc.json
  .prettierrc.json
  .remarkrc.json
  .stylelintrc.json
  CONTRIBUTING.md
  package.json
Labels: bug, infrastructure

#5516 chore(i18n): crowdin sync
  i18n/locales/id.json
  i18n/locales/zh-cn.json
  pages/id/docs/index.mdx
  pages/zh-cn/docs/guides/event-loop-timers-and-nexttick.md
  pages/zh-cn/docs/index.mdx
Labels: i18n, crowdin

#5524 chore: updated turborepo config
  .github/workflows/build-and-analysis.yml
  .github/workflows/pull-request.yml
  turbo.json
Labels: github_actions, fast-track, infrastructure

#5525 chore: better cache on actions
  .github/workflows/build-and-analysis.yml
  .github/workflows/pull-request.yml
Labels: github_actions, fast-track, infrastructure

#5530 fix: storybook flakiness and minor typescript issues
  .gitignore
  .storybook/main.ts
  .storybook/test-runner.ts
  components/Article/AuthorList/Author/__snapshots__/index.stories.tsx.snap
  components/Article/AuthorList/__snapshots__/index.stories.tsx.snap
  components/Common/index.ts
  components/__fixtures__/nodeReleases.tsx
  hooks/__tests__/useMediaQuery.test.tsx
  package-lock.json
  package.json
Labels: fast-track

#5534 fix: 404 generation and circular dependencies
  next.constants.mjs
  pages/404.tsx
  theme.tsx
Labels: bug, fast-track, infrastructure

#5539 fix: make prettier fix style files
  .lintstagedrc.json
  package.json
Labels: bug, fast-track

#5549 chore: dependabot be more precise
  .github/dependabot.yml
Labels: fast-track

#5548 feat: jest comments, remote storybook and only ubuntu runners
  .eslintignore
  .github/workflows/build-and-analysis.yml
  .github/workflows/pull-request.yml
  .gitignore
  .prettierignore
  .storybook/main.ts
  .storybook/test-runner.ts
  CONTRIBUTING.md
  components/Article/AuthorList/Author/__snapshots__/index.stories.tsx.snap
  components/Article/AuthorList/__snapshots__/index.stories.tsx.snap
  components/Article/EditLink/__snapshots__/index.stories.tsx.snap
  components/Blog/BlogCard/__snapshots__/index.stories.tsx.snap
  components/Common/AnimatedPlaceholder/__snapshots__/index.stories.tsx.snap
  components/Common/AnimatedPlaceholder/index.stories.tsx
  components/Common/Banner/__snapshots__/index.stories.tsx.snap
  components/Learn/PreviousNextLink/__snapshots__/index.stories.tsx.snap
  components/Sections/NewFooter/__snapshots__/index.stories.tsx.snap
  components/Sections/NewHeader/__snapshots__/index.stories.tsx.snap
  jest.config.mjs
  package.json
  turbo.json
Labels: github_actions, infrastructure

#5569 meta: workflow updates (heavy documentation + local storybook + turbo remote cache fixes)
  .github/workflows/build-and-analysis.yml
  .github/workflows/pull-request.yml
  package-lock.json
  package.json
Labels: github_actions, fast-track, infrastructure

#5577 chore: pull request target for checks
  .github/workflows/build.yml
  .github/workflows/pull-request-target.yml
  .github/workflows/pull-request.yml
  README.md
Labels: github_actions, fast-track, infrastructure

#5580 feat: add nginx rewrites
  next.config.mjs
  next.rewrites.mjs
Labels: fast-track

#5582 fix: add missing releases page link
  next.rewrites.mjs
Labels: fast-track

#5590 fix: symmetric git diff due to head behind base
  .github/workflows/pull-request.yml
Labels: fast-track
