Repository nodejs/nodejs.org, pull requests merged in 2023-08, with the labels that each got.

#5581 docs: clarify approvers for new blog posts
  CONTENT_VS_CODE.md
Labels: fast-track

#5587 chore: improve redirects
  next.rewrites.mjs
Labels: fast-track, infrastructure

#5592 chore: configuration for merge queues
  .github/workflows/build.yml
  .github/workflows/pull-request-target.yml
  .github/workflows/pull-request.yml
Labels: github_actions, fast-track

#5583 meta: added chromatic for visual regression tests
  .github/workflows/build.yml
  .github/workflows/pull-request-target.yml
  .github/workflows/pull-request.yml
  .storybook/test-runner.ts
  CONTRIBUTING.md
  README.md
  components/Api/ApiChanges/__snapshots__/index.stories.tsx.snap
  components/Api/DataTag/__snapshots__/index.stories.ts.snap
  components/Api/JsonLink/__snapshots__/index.stories.ts.snap
  components/Api/SourceLink/__snapshots__/index.stories.ts.snap
  components/Api/Stability/__snapshots__/index.stories.tsx.snap
  components/Article/Alert/__snapshots__/index.stories.ts.snap
  components/Article/AuthorList/Author/__snapshots__/index.stories.tsx.snap
  components/Article/AuthorList/__snapshots__/index.stories.tsx.snap
  components/Article/BlockQuote/__snapshots__/index.stories.tsx.snap
  components/Article/Codebox/__snapshots__/index.stories.tsx.snap
  components/Article/EditLink/__snapshots__/index.stories.tsx.snap
  components/Article/InlineCode/__snapshots__/index.stories.tsx.snap
  components/Blog/BlogCard/__snapshots__/index.stories.tsx.snap
  components/Common/AnimatedPlaceholder/__snapshots__/index.stories.tsx.snap
  components/Common/Banner/__snapshots__/index.stories.tsx.snap
  components/Common/DarkModeToggle/__snapshots__/index.stories.tsx.snap
  components/Common/Dropdown/__snapshots__/index.stories.tsx.snap
  components/Common/LanguageSelector/__snapshots__/index.stories.tsx.snap
  components/Common/SectionTitle/__snapshots__/index.stories.ts.snap
  components/Downloads/DownloadToggle/__snapshots__/index.stories.tsx.snap
  components/Home/NodeFeatures/__snapshots__/index.stories.tsx.snap
  components/Learn/PreviousNextLink/__snapshots__/index.stories.tsx.snap
  components/Sections/NewFooter/__snapshots__/index.stories.tsx.snap
  components/Sections/NewHeader/__snapshots__/index.stories.tsx.snap
  package-lock.json
  package.json
  turbo.json
Labels: github_actions, infrastructure

#5600 chore(i18n): crowdin sync
  pages/be/about/index.md
  pages/be/docs/guides/diagnostics/live-debugging/index.md
  pages/be/download/releases.md
Labels: i18n, crowdin

#5614 chore: fix robots generation and updated ignore files
  .eslintignore
  .gitignore
  .prettierignore
  next.config.mjs
  next.rewrites.mjs
  package.json
  robots.config.mjs
Labels: fast-track

#5613 chore: node_env as global env
  middleware.ts
  middlewares/detectLanguage.ts
  next.middleware.ts
  turbo.json
  types/index.ts
  types/middlewares.ts
Labels: fast-track

#5618 fix: main download button for linux incorrect
  util/downloadUrlByOS.ts
Labels: fast-track

#5615 feat: introduced json file for redirects
  next.config.mjs
  next.constants.mjs
  next.dynamic.mjs
  next.json.mjs
  next.locales.mjs
  next.rewrites.mjs
  redirects.json
Labels: infrastructure

#5626 chore: added inspector redirect
  redirects.json
Labels: fast-track

#5637 fix: lint-staged to run stylelint
  .lintstagedrc.json
Labels: infrastructure

#5638 feat: introduced alternate hreflangs for all the available languages
  app/en/feed/[feed]/route.ts
  app/sitemap.xml/route.ts
  components/HtmlHead.tsx
  hooks/useLocale.ts
  hooks/useNavigation.tsx
  hooks/useRouter.ts
  next-data/generateWebsiteFeeds.mjs
  next.dynamic.mjs
  pages/[...path].tsx
  pages/_document.tsx
  providers/localeProvider.tsx
  providers/siteProvider.tsx
  robots.config.mjs
  types/i18n.ts
Labels: i18n, infrastructure

#5612 chore(i18n): crowdin sync
  pages/uk/about/index.md
  pages/uk/docs/guides/diagnostics/live-debugging/index.md
  pages/uk/docs/guides/diagnostics/live-debugging/using-inspector.md
  pages/uk/docs/index.mdx
  pages/uk/get-involved/collab-summit.md
  pages/uk/get-involved/contribute.md
Labels: i18n, crowdin

#5641 chore(i18n): crowdin sync
  pages/uk/404.md
Labels: i18n, crowdin

#5665 chore(i18n): crowdin sync
  pages/ja/about/index.md
Labels: i18n, crowdin

#5692 Remove ApiChanges component
  components/Api/ApiChanges/index.module.scss
  components/Api/ApiChanges/index.stories.tsx
  components/Api/ApiChanges/index.tsx
  i18n/locales/en.json
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: fast-track

#5693 feat: remove inlineCode component
  components/Article/InlineCode/index.module.scss
  components/Article/InlineCode/index.stories.tsx
  components/Article/InlineCode/index.tsx
Labels: fast-track

#5694 feat: remove EditLink component
  components/Article/EditLink/__tests__/index.test.mjs
  components/Article/EditLink/index.module.scss
  components/Article/EditLink/index.stories.tsx
  components/Article/EditLink/index.tsx
  i18n/locales/en.json
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: fast-track

#5708 chore: delete Stability component
  components/Api/Stability/index.module.scss
  components/Api/Stability/index.stories.tsx
  components/Api/Stability/index.tsx
  i18n/locales/en.json
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: fast-track

#5716 fix: fix bad merge
  i18n/locales/en.json
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: fast-track

#5717 chore: delete Author and AuthorList components
  components/Article/AuthorList/Author/index.module.scss
  components/Article/AuthorList/Author/index.stories.tsx
  components/Article/AuthorList/Author/index.tsx
  components/Article/AuthorList/index.module.scss
  components/Article/AuthorList/index.stories.tsx
  components/Article/AuthorList/index.tsx
  i18n/locales/en.json
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: fast-track

#5721 chore(i18n): crowdin sync
  pages/be/about/governance.md
  pages/ko/get-involved/index.md
  pages/zh-cn/get-involved/index.md
Labels: i18n, crowdin

#5727 chore: delete DownloadToggle component
  components/Downloads/DownloadToggle/__tests__/index.test.mjs
  components/Downloads/DownloadToggle/index.module.scss
  components/Downloads/DownloadToggle/index.stories.tsx
  components/Downloads/DownloadToggle/index.tsx
  i18n/locales/en.json
  i18n/locales/id.json
  i18n/locales/zh-cn.json
Labels: fast-track

#5728 meta: remove non-useful bundle analysis generation
  .github/workflows/build.yml
  .github/workflows/pull-request-target.yml
  .github/workflows/pull-request.yml
Labels: fast-track
