Repository nodejs/nodejs.org, pull requests merged in 2023-05, with the labels that each got.

#5332 chore: adopt @nodevu/core and remove node-version-data
  components/Docs/NodeApiVersionLinks.tsx
  package-lock.json
  package.json
  scripts/next-data/getNodeVersionData.mjs
Labels: infrastructure

#5234 (website redesign) Feat(shellbox): migration
  components/Common/ShellBox/__tests__/__snapshots__/index.test.tsx.snap
  components/Common/ShellBox/__tests__/index.test.tsx
  components/Common/ShellBox/index.module.scss
  components/Common/ShellBox/index.stories.tsx
  components/Common/ShellBox/index.tsx
  components/Common/index.ts
  hooks/__test__/useCopyToClipboard.test.tsx
  hooks/useCopyToClipboard.ts
  i18n/locales/en.json
Labels: website redesign

#5370 Migrate JsonLink component
  components/Api/JsonLink/__snapshots__/index.stories.ts.snap
  components/Api/JsonLink/index.module.scss
  components/Api/JsonLink/index.stories.ts
  components/Api/JsonLink/index.tsx
  i18n/locales/en.json
Labels: website redesign

#5384 feat: introduce built-in next.js exports and updated scripts and configs
  .gitignore
  CONTRIBUTING.md
  next-sitemap.config.js
  next-sitemap.config.mjs
  next.config.mjs
  package-lock.json
  package.json
  public/robots.txt
  scripts/next-data/generatePreBuildFiles.mjs
  scripts/next-data/getBlogData.mjs
  scripts/next-data/getLocalisationData.mjs
  scripts/release-post/index.mjs
  turbo.json
Labels: fast-track

#5391 fix(link): 404
  pages/en/download/package-manager.md
Labels: fast-track
