Repository nodejs/nodejs.org, pull requests merged in 2023-10, with the labels that each got.

#5932 chore: apply eslint import rules on all js files
  .eslintrc.json
  components/Common/ActiveLocalizedLink/__tests__/index.test.mjs
  hooks/__tests__/useClickOutside.test.mjs
  hooks/__tests__/useCopyToClipboard.test.mjs
  hooks/__tests__/useDetectOS.test.mjs
  hooks/__tests__/useMediaQuery.test.mjs
  next-data/generateBlogPostsData.mjs
  next-data/generateNodeReleasesJson.mjs
  next-data/generateWebsiteFeeds.mjs
  next.data.mjs
  next.dynamic.mjs
  next.helpers.mjs
  next.json.mjs
  next.locales.mjs
  scripts/release-post/index.mjs
Labels: fast-track

#5930 fix: merged js logos and fixed svgs
  components/__design__/colors.stories.tsx
  components/__design__/font-family.stories.tsx
  components/__design__/hex-logos.stories.tsx
  components/__design__/horizontal-logos.stories.tsx
  components/__design__/js-logos.stories.tsx
  components/__design__/node-logos.stories.tsx
  components/__design__/platform-logos.stories.tsx
  components/__design__/social-logos.stories.tsx
  components/__design__/stacked-logos.stories.tsx
  public/static/images/logos/horizontal-dark.svg
  public/static/images/logos/horizontal-light.svg
  public/static/images/logos/js-white.svg
  public/static/images/logos/platform-linux.svg
  public/static/images/logos/social-github-dark.svg
  public/static/images/logos/social-github.svg
  public/static/images/logos/social-linkedin.svg
  public/static/images/logos/social-mastodon.svg
  public/static/images/logos/social-x.svg
Labels: fast-track

#5923 fix: some npm settings tweaks
  .npmrc
  package-lock.json
  package.json
Labels: infrastructure

#5953 fix: use twitter icon
  components/__design__/social-logos.stories.tsx
  public/static/images/logos/social-twitter.svg
  public/static/images/logos/social-x.svg
Labels: fast-track, website redesign

#5956 fix: Banner component text color and spacing
  components/Common/Banner/index.module.css
Labels: fast-track

#5952 Style: Added inline code styling
  .storybook/constants.ts
  .storybook/preview.tsx
  components/__design__/text.stories.tsx
  styles/new/base.css
  tailwind.config.ts
Labels: hacktoberfest

#5962 Chore: Add platform icon nvm
  components/__design__/platform-logos.stories.tsx
  public/static/images/logos/platform-nvm.svg
Labels: fast-track, hacktoberfest

#5957 Style: Add unordered and ordered list styling
  components/__design__/list.stories.tsx
  styles/new/base.css
Labels: hacktoberfest

#5963 feat: InlineSelect ability
  components/Common/Select/index.module.css
  components/Common/Select/index.stories.tsx
  components/Common/Select/index.tsx
  styles/new/base.css
Labels: hacktoberfest

#5955 Create Notification Component
  .storybook/preview.tsx
  components/Common/Notification/index.module.css
  components/Common/Notification/index.stories.tsx
  components/Common/Notification/index.tsx
  hooks/useNotification.ts
  i18n/locales/en.json
  package-lock.json
  package.json
  providers/notificationProvider.tsx
Labels: hacktoberfest

#5972 Create NavItem component
  components/sections/NavItem/index.module.css
  components/sections/NavItem/index.stories.tsx
  components/sections/NavItem/index.tsx
Labels: hacktoberfest

#5928 feat(components): add `Breadcrumbs` component
  components/Common/Breadcrumbs/BreadcrumbHomeLink/index.module.css
  components/Common/Breadcrumbs/BreadcrumbHomeLink/index.tsx
  components/Common/Breadcrumbs/BreadcrumbItem/index.module.css
  components/Common/Breadcrumbs/BreadcrumbItem/index.tsx
  components/Common/Breadcrumbs/BreadcrumbLink/index.module.css
  components/Common/Breadcrumbs/BreadcrumbLink/index.tsx
  components/Common/Breadcrumbs/BreadcrumbRoot/index.module.css
  components/Common/Breadcrumbs/BreadcrumbRoot/index.tsx
  components/Common/Breadcrumbs/BreadcrumbTruncatedItem/index.tsx
  components/Common/Breadcrumbs/index.stories.tsx
  components/Common/Breadcrumbs/index.tsx
  i18n/locales/en.json
Labels: hacktoberfest

#5971 Feat: create Common/Pagination component
  .eslintrc.json
  __mocks__/nextJsRouter.mjs
  components/Common/ActiveLocalizedLink/__tests__/index.test.mjs
  components/Common/Pagination/Ellipsis/index.module.css
  components/Common/Pagination/Ellipsis/index.tsx
  components/Common/Pagination/PaginationListItem/__tests__/index.test.mjs
  components/Common/Pagination/PaginationListItem/index.module.css
  components/Common/Pagination/PaginationListItem/index.tsx
  components/Common/Pagination/__tests__/index.test.mjs
  components/Common/Pagination/index.module.css
  components/Common/Pagination/index.stories.tsx
  components/Common/Pagination/index.tsx
  components/Common/Pagination/useGetPageElements.tsx
  i18n/locales/en.json
  jest.setup.mjs
  tailwind.config.ts
Labels: hacktoberfest

#5978 fix: add remark-gfm
  .remarkrc.json
  next.dynamic.mjs
  package-lock.json
  package.json
Labels: fast-track

#5992 blog: update references to SECURITY.md
  pages/en/blog/vulnerability/august-2023-security-releases.md
  pages/en/blog/vulnerability/february-2023-security-releases.md
  pages/en/blog/vulnerability/june-2023-security-releases.md
  pages/en/blog/vulnerability/november-2022-security-releases.md
  pages/en/blog/vulnerability/october-2023-security-releases.md
  pages/en/blog/vulnerability/september-2022-security-releases.md
Labels: content

#5983 Create Footer Component
  components/sections/Footer/index.module.css
  components/sections/Footer/index.stories.tsx
  components/sections/Footer/index.tsx
  components/sections/NavItem/index.stories.tsx
  components/sections/NavItem/index.tsx
  i18n/locales/en.json
  providers/siteProvider.tsx
  site.json
  types/config.ts
Labels: hacktoberfest

#5999 performance, bundle and standardisation changes
  .eslintrc.json
  .nvmrc
  .remarkrc.json
  COLLABORATOR_GUIDE.md
  __mocks__/nextJsRouter.mjs
  components/__fixtures__/nodeReleases.tsx
  components/__mocks__/next-router.mjs
  jest.config.mjs
  jest.setup.mjs
  next.config.mjs
  next.dynamic.mjs
  next.mdast.mjs
  package-lock.json
  package.json
  postcss.config.js
  shiki.config.mjs
Labels: infrastructure

#6006 fix: remark-lint, caches and preset-lint-node
  .github/workflows/lint-and-tests.yml
  .gitignore
  .prettierignore
  .remarkrc.json
  COLLABORATOR_GUIDE.md
  package-lock.json
  package.json
  pages/id/docs/guides/backpressuring-in-streams.md
  pages/tr/about/governance.md
  pages/uk/get-involved/contribute.md
  turbo.json
Labels: fast-track, infrastructure

#6015 fix: Revert download link labels
  pages/ja/download/current.md
  pages/ja/download/index.md
  pages/ru/download/current.md
  pages/ru/download/index.md
  pages/uk/download/current.md
  pages/uk/download/index.md
  pages/zh-tw/download/current.md
  pages/zh-tw/download/index.md
Labels: fast-track

#5982 Component/language drop down
  components/Common/LanguageDropDown/index.module.css
  components/Common/LanguageDropDown/index.stories.tsx
  components/Common/LanguageDropDown/index.tsx
  hooks/__tests__/useClickOutside.test.mjs
  hooks/useClickOutside.ts
  i18n/locales/en.json
  package-lock.json
  package.json
Labels: hacktoberfest

#6010 feat: MetaBar Component
  components/Common/AvatarGroup/index.module.css
  components/Common/MetaBar/index.module.css
  components/Common/MetaBar/index.stories.tsx
  components/Common/MetaBar/index.tsx
  i18n/locales/en.json
Labels: hacktoberfest

#6014 feat(Preview): add Preview component
  components/Common/Preview/index.module.css
  components/Common/Preview/index.stories.tsx
  components/Common/Preview/index.tsx
  public/static/images/patterns/hexagon-grid.svg
  tailwind.config.ts
Labels: hacktoberfest

#6025 fix: maintenance lts in the lack of active lts
  hooks/useNodeReleases.ts
  layouts/DocsLayout.tsx
  layouts/DownloadLayout.tsx
  layouts/IndexLayout.tsx
  next.json.mjs
  providers/nodeReleasesProvider.tsx
  providers/withNodeRelease.tsx
Labels: fast-track

#6029 fix: update location of `using-heap-snapshot.md`
  pages/en/docs/guides/diagnostics/memory/using-gc-traces.md
Labels: fast-track

#6034 Added Table Styling Based on Figma Design for Node.js Website
  components/__design__/table.stories.tsx
  styles/new/base.css
Labels: hacktoberfest

#6046 meta: some component cleanups and design fixes
  COLLABORATOR_GUIDE.md
  components/Common/AvatarGroup/Avatar/index.stories.tsx
  components/Common/AvatarGroup/index.stories.tsx
  components/Common/AvatarGroup/index.tsx
  components/Common/Badge/index.stories.tsx
  components/Common/Banner/index.stories.tsx
  components/Common/Blockquote/index.stories.tsx
  components/Common/Breadcrumbs/index.stories.tsx
  components/Common/Breadcrumbs/index.tsx
  components/Common/Button/index.stories.tsx
  components/Common/Button/index.tsx
  components/Common/CrossLink/index.stories.tsx
  components/Common/LanguageDropDown/index.module.css
  components/Common/LanguageDropDown/index.stories.tsx
  components/Common/LanguageDropDown/index.tsx
  components/Common/MetaBar/index.stories.tsx
  components/Common/Notification/index.stories.tsx
  components/Common/Pagination/PaginationListItem/index.tsx
  components/Common/Pagination/index.stories.tsx
  components/Common/Pagination/index.tsx
  components/Common/Pagination/useGetPageElements.tsx
  components/Common/Preview/index.stories.tsx
  components/Common/Select/index.stories.tsx
  components/Common/Tabs/index.stories.tsx
  components/Common/Time/index.tsx
Labels: fast-track

#6044 chore: formatting release post
  scripts/release-post/index.mjs
Labels: hacktoberfest

#6037 Feat: create Common/BlogPostCard component
  components/Common/AvatarGroup/Avatar/index.module.css
  components/Common/BlogPostCard/__tests__/index.test.mjs
  components/Common/BlogPostCard/index.module.css
  components/Common/BlogPostCard/index.stories.tsx
  components/Common/BlogPostCard/index.tsx
  components/Common/Preview/index.tsx
  i18n/locales/en.json
Labels: hacktoberfest

#6050 meta: switch to shikiji and updated packages
  .postcssrc.json
  next.mdx.mjs
  package-lock.json
  package.json
  pages/en/blog/announcements/v21-release-announce.md
  postcss.config.js
  shiki.config.mjs
Labels: fast-track, infrastructure

#6054 fix: use rehype-shikiji
  components/Common/BlogPostCard/index.stories.tsx
  next.config.mjs
  next.mdx.mjs
  package-lock.json
  package.json
  pages/en/docs/guides/nodejs-docker-webapp.md
  shiki.config.mjs
Labels: fast-track, infrastructure

#6055 fix: Syntax highlighter empty line
  styles/old/index.css
Labels: fast-track
