Repository nodejs/nodejs.org, pull requests merged in 2024-05, with the labels that each got.

#6674 build(script): use `dev` instead of `serve`
  CONTRIBUTING.md
  README.md
  package.json
  turbo.json
Labels: infrastructure

#6467 feat(metabar): Add avatarGroup on learn section
  components/Common/AvatarGroup/Avatar/index.tsx
  components/Common/AvatarGroup/index.module.css
  components/Containers/MetaBar/index.module.css
  components/Containers/MetaBar/index.stories.tsx
  components/withMetaBar.tsx
  types/frontmatter.ts
Labels: design, website redesign

#6722 fix: change NVM to nvm
  util/downloadUtils.ts
  util/getNodeDownloadSnippet.ts
Labels: fast-track

#6727 docs(README): clarify how our styles are applied
  README.md
Labels: fast-track
