Repository nodejs/nodejs.org, pull requests merged in 2024-03, with the labels that each got.

#6395 fix: download button icon
  components/Downloads/DownloadButton/index.tsx
Labels: fast-track

#6406 fix(footer): update Privacy and Trademark Policy links
  site.json
Labels: fast-track

#6408 Fixed Issue #6394: Hid event button
  layouts/Blog.tsx
Labels: fast-track

#6410 fix: remove select item flex to enable truncation, add left spacing for items
  components/Common/Select/index.module.css
  components/Common/Select/index.tsx
Labels: fast-track

#6415 chore(pr-template): remove `lint` command and add `build`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fast-track

#6411 Fix #6404 : Version dropdown on download page doesn't scroll on overflow
  components/Common/Select/index.module.css
Labels: fast-track

#6449 fix: bg on `LanguageDropDown`
  components/Common/LanguageDropDown/index.module.css
Labels: design, website redesign

#6450 feat(download):color link on botton in dark and light mode
  components/Downloads/Release/LinkWithArrow.tsx
Labels: design, fast-track, website redesign

#6455 fix: zoom issue on smaller screens due to focus
  next.dynamic.constants.mjs
Labels: fast-track, website redesign

#6452 fix: select should have scrollbar
  components/Common/Select/__tests__/index.test.mjs
  components/Common/Select/index.tsx
  package-lock.json
  package.json
Labels: website redesign

#6464 blog: mention Hemanth to styleText api
  pages/en/blog/release/v21.7.0.md
Labels: fast-track

#6466 fix: remove .hbs on branding
  pages/en/about/branding.mdx
Labels: bug, good first issue, fast-track, website redesign

#6469 [legacy] Blog: v21.7.1 release post
  pages/en/blog/release/v21.7.1.md
Labels: github_actions:pull-request

#6471 chore: remove corepack mention
  pages/en/download/current.mdx
  pages/en/download/index.mdx
  pages/en/download/package-manager/current.mdx
  pages/en/download/package-manager/index.mdx
  pages/en/download/prebuilt-binaries/current.mdx
  pages/en/download/prebuilt-binaries/index.mdx
  pages/en/download/source-code/current.mdx
  pages/en/download/source-code/index.mdx
Labels: fast-track

#6473 chore: update incorrect code comments regarding dynamicParams
  app/[locale]/feed/[feed]/route.ts
  app/[locale]/next-data/og/route.tsx
Labels: fast-track

#6474 chore: Orama remote image pattern
  next.config.mjs
Labels: fast-track, website redesign

#6482 Update introduction-to-nodejs.md
  pages/en/about/index.mdx
  pages/en/learn/getting-started/introduction-to-nodejs.md
Labels: fast-track

#6497 Reverts #6478 - removes debounce on search
  components/Common/Search/States/WithSearchBox.tsx
Labels: fast-track

#6507 add Orama to thanks
  README.md
Labels: fast-track

#6517 feat(icons): use "x" instead of the bird
  components/Icons/Social/Twitter.tsx
Labels: fast-track

#6518 chore(Translation): update translation policy
  TRANSLATION.md
Labels: i18n

#6519 Polish Translations Setup
  i18n/config.json
Labels: i18n

#6496 Added Romanian locale
  i18n/config.json
Labels: i18n

#6545 fix(og): use the resolved page title
  next.dynamic.mjs
Labels: fast-track

#6523 feat: Mark external links in the sidebar
  components/Containers/Sidebar/SidebarItem/index.module.css
  components/Containers/Sidebar/SidebarItem/index.tsx
Labels: fast-track

#6547 Fixes search page with no query should not throw
  components/MDX/SearchPage/index.tsx
  package-lock.json
  package.json
Labels: fast-track

#6533 fix:layout-shift caused by the radix dropdown menu.
  styles/base.css
Labels: fast-track

#6525 fix: Disable text selection for <Select> options
  components/Common/Select/index.module.css
Labels: fast-track

#6548 Chore: add searchbar shortcut indicator
  components/Common/Search/index.module.css
  components/Common/Search/index.tsx
Labels: fast-track

#6578 blog: add banner for April security release
  site.json
Labels: fast-track
