Repository nodejs/nodejs.org, pull requests merged in 2024-11, with the labels that each got.

#7196 fix: Select component highlighted text color
  apps/site/components/Common/Select/index.module.css
Labels: bug, fast-track

#7182 Fix typo: Update anatomy-of-an-http-transaction.md
  apps/site/pages/en/learn/modules/anatomy-of-an-http-transaction.md
Labels: learn

#7143 feat: Introducing avatar tooltip
  apps/site/components/Common/AvatarGroup/Avatar/index.module.css
  apps/site/components/Common/AvatarGroup/Avatar/index.stories.tsx
  apps/site/components/Common/AvatarGroup/Avatar/index.tsx
  apps/site/components/Common/AvatarGroup/Overlay/index.module.css
  apps/site/components/Common/AvatarGroup/Overlay/index.stories.tsx
  apps/site/components/Common/AvatarGroup/Overlay/index.tsx
  apps/site/components/Common/AvatarGroup/__tests__/index.test.mjs
  apps/site/components/Common/AvatarGroup/index.stories.tsx
  apps/site/components/Common/AvatarGroup/index.tsx
  apps/site/components/Common/BlogPostCard/__tests__/index.test.mjs
  apps/site/components/Common/BlogPostCard/index.module.css
  apps/site/components/Common/BlogPostCard/index.stories.tsx
  apps/site/components/Common/BlogPostCard/index.tsx
  apps/site/components/Common/Tooltip/index.module.css
  apps/site/components/Common/Tooltip/index.stories.tsx
  apps/site/components/Common/Tooltip/index.tsx
  apps/site/components/Containers/MetaBar/index.stories.tsx
  apps/site/components/Downloads/Release/LinkWithArrow.tsx
  apps/site/components/withAvatarGroup.tsx
  apps/site/components/withBlogCategories.tsx
  apps/site/components/withMetaBar.tsx
  apps/site/layouts/Post.tsx
  apps/site/next.config.mjs
  apps/site/package.json
  apps/site/types/author.ts
  apps/site/types/config.ts
  apps/site/types/index.ts
  apps/site/util/__tests__/authorUtils.test.mjs
  apps/site/util/__tests__/blogUtils.test.mjs
  apps/site/util/authorUtils.ts
  apps/site/util/blogUtils.ts
  package-lock.json
Labels: enhancement, design

#7238 content: synchronize contribute page with GOVERNANCE.md
  apps/site/pages/en/about/get-involved/contribute.md
Labels: content, learn

#7234 chore: update dependencies
  apps/site/package.json
  package-lock.json
  package.json
  packages/i18n/package.json
Labels: infrastructure

#7253 infra: add `@oramacloud/*` to dependabot
  .github/dependabot.yml
Labels: infrastructure

#7270 fix(cache): remove cache rules from fetch()
  apps/site/app/[locale]/next-data/api-data/route.ts
  apps/site/next-data/blogData.ts
  apps/site/next-data/releaseData.ts
  apps/site/next.calendar.mjs
Labels: fast-track

#7276 fix: align mdx
  apps/site/pages/en/index.mdx
  apps/site/pages/es/index.mdx
  apps/site/pages/fa/index.mdx
  apps/site/pages/fr/index.mdx
  apps/site/pages/id/index.mdx
  apps/site/pages/ja/index.mdx
  apps/site/pages/ko/index.mdx
  apps/site/pages/pt/index.mdx
  apps/site/pages/tr/index.mdx
  apps/site/pages/uk/index.mdx
  apps/site/pages/zh-cn/index.mdx
  apps/site/pages/zh-tw/index.mdx
  apps/site/tsconfig.json
Labels: fast-track

#7280 chore: simplified storybook/next config
  apps/site/.storybook/main.ts
  apps/site/next.config.mjs
  apps/site/turbo.json
Labels: fast-track

#7282 meta: upgrade to node v22
  .nvmrc
  apps/site/package.json
  package-lock.json
  package.json
  packages/i18n/package.json
Labels: fast-track

#7291 hotfix: only one og
  apps/site/next.dynamic.mjs
Labels: fast-track
