Repository nodejs/nodejs.org, pull requests merged in 2024-12, with the labels that each got.

#7311 feat(banner): add cyber week
  apps/site/site.json
Labels: fast-track

#7229 feat(learn): add Package Configuration article
  apps/site/navigation.json
  apps/site/pages/en/learn/modules/publishing-a-package.mdx
  packages/i18n/locales/en.json
Labels: content, learn

#7356 feat: IBM AIX Icon added
  apps/site/components/Common/Select/index.stories.tsx
  apps/site/components/Downloads/Release/OperatingSystemDropdown.tsx
  apps/site/components/Icons/Platform/AIX.tsx
  apps/site/components/__design__/platform-logos.stories.tsx
Labels: fast-track

#7361 chore: fix lighthouse workflow
  .github/workflows/lighthouse.yml
Labels: fast-track

#7360 download: restore preamble in download snippets
  apps/site/snippets/en/download/brew.bash
  apps/site/snippets/en/download/choco.bash
  apps/site/snippets/en/download/docker.bash
  apps/site/snippets/en/download/fnm.bash
  apps/site/snippets/en/download/nvm.bash
Labels: fast-track

#7366 fix: compatibility engine should run even on initial state
  apps/site/components/Downloads/Release/OperatingSystemDropdown.tsx
  apps/site/components/Downloads/Release/PackageManagerDropdown.tsx
  apps/site/components/Downloads/Release/PlatformDropdown.tsx
  apps/site/components/Downloads/Release/PrebuiltDownloadButtons.tsx
  apps/site/util/downloadUtils.tsx
Labels: fast-track

#7368 fix: numerous minor improvements and fixes for downloads page
  apps/site/components/Common/AlertBox/index.tsx
  apps/site/components/Downloads/Release/OperatingSystemDropdown.tsx
  apps/site/components/Downloads/Release/ReleaseCodeBox.tsx
  apps/site/hooks/react-client/__tests__/useMediaQuery.test.mjs
  apps/site/hooks/react-client/useMediaQuery.ts
  apps/site/navigation.json
  apps/site/pages/es/search.mdx
  apps/site/util/downloadUtils.tsx
  packages/i18n/locales/en.json
Labels: fast-track

#7123 feat: add streams guide
  apps/site/navigation.json
  apps/site/pages/en/learn/modules/how-to-use-streams.md
  packages/i18n/locales/en.json
Labels: learn
