Repository nodejs/nodejs.org, pull requests merged in 2024-02, with the labels that each got.

#6350 feat(blog): add visible RSS feed
  components/Blog/BlogHeader/__tests__/index.test.mjs
  components/Blog/BlogHeader/index.module.css
  components/Blog/BlogHeader/index.stories.tsx
  components/Blog/BlogHeader/index.tsx
  layouts/New/Blog.tsx
  layouts/New/layouts.module.css
  types/features.ts
Labels: design, website redesign

#6257 Integrate Orama for search
  .github/workflows/build.yml
  .gitignore
  app/[locale]/next-data/page-data/route.ts
  components/Common/Search/States/WithAllResults.tsx
  components/Common/Search/States/WithEmptyState.tsx
  components/Common/Search/States/WithError.tsx
  components/Common/Search/States/WithNoResults.tsx
  components/Common/Search/States/WithPoweredBy.tsx
  components/Common/Search/States/WithSearchBox.tsx
  components/Common/Search/States/WithSearchResult.tsx
  components/Common/Search/States/index.module.css
  components/Common/Search/index.module.css
  components/Common/Search/index.tsx
  components/Common/Search/utils.ts
  components/Containers/NavBar/index.tsx
  components/MDX/SearchPage/index.module.css
  components/MDX/SearchPage/index.tsx
  components/withLayout.tsx
  hooks/react-client/index.ts
  hooks/react-client/useBottomScrollListener.ts
  hooks/react-client/useClickOutside.ts
  hooks/react-client/useKeyboardCommands.ts
  i18n/locales/en.json
  layouts/New/Search.tsx
  next.constants.mjs
  next.mdx.use.mjs
  next.orama.mjs
  package-lock.json
  package.json
  pages/en/search.mdx
  scripts/orama-search/get-documents.mjs
  scripts/orama-search/sync-orama-cloud.mjs
  turbo.json
  types/index.ts
  types/layouts.ts
  types/search.ts
  util/__tests__/stringUtils.test.mjs
  util/debounce.ts
  util/stringUtils.ts
Labels: website redesign

#6355 fix: Use Tux mascot for Linux icon
  components/Icons/Platform/Linux.tsx
Labels: fast-track

#6359 docs(package-manager): IBM i use recent node version
  pages/en/download/package-manager.md
Labels: fast-track
