Repository nodejs/nodejs.org, pull requests merged in 2024-04, with the labels that each got.

#6586 fix: properly tag maintenance and flag versions correctly
  components/Downloads/Release/VersionDropdown.tsx
  components/withDownloadCategories.tsx
  next-data/generators/releaseData.mjs
  pages/en/index.mdx
  types/releases.ts
Labels: fast-track

#6543 feat(tabs): fix contrast ratio
  components/Common/CodeTabs/index.module.css
  components/Common/CodeTabs/index.tsx
  components/Common/Tabs/index.tsx
Labels: design

#6604 fix: update collab-summit.md
  pages/en/about/get-involved/collab-summit.md
Labels: fast-track

#6607 fix: Banner type
  components/Downloads/ChangelogModal/index.module.css
  site.json
Labels: design

#6619 fix: Search box button accessibility
  components/Common/Search/index.module.css
  components/Common/Search/index.tsx
Labels: accessibility

#6634 FIx sentry integrations lazy loading
  sentry.client.config.ts
Labels: infrastructure

#6681 fix: svg warning in HexagonGrid
  components/Icons/HexagonGrid.tsx
Labels: fast-track
