Repository nodejs/nodejs.org, pull requests merged in 2025-03, with the labels that each got.

#7493 learn: Update Don't Block the Event Loop outdated remark about `fs.readFile()`
  apps/site/pages/en/learn/asynchronous-work/dont-block-the-event-loop.md
Labels: content, learn

#7556 Blog: synchronize v20.19.0 changelog with core repo
  apps/site/pages/en/blog/release/v20.19.0.md
Labels: content, fast-track

#7006 feat(learn): Collecting code coverage
  apps/site/navigation.json
  apps/site/pages/en/learn/test-runner/collecting-code-coverage.md
  packages/i18n/locales/en.json
Labels: content, learn

#7571 fix: apply tailwind to `tsx` files in `ui-components`
  apps/site/styles/index.css
  apps/site/styles/locales.css
  apps/site/tailwind.config.ts
  packages/ui-components/styles/markdown.css
Labels: fast-track

#7572 fix: apply correct styles to `sidebarItemToggler`
  packages/ui-components/Containers/NavBar/index.tsx
Labels: fast-track

#7573 fix: add more styles to ui-components
  apps/site/styles/index.css
  packages/ui-components/styles/base.css
  packages/ui-components/styles/index.css
Labels: fast-track

#7584 chore(actions): update chromaui
  .github/workflows/lint-and-tests.yml
Labels: fast-track
