Repository nodejs/nodejs.org, pull requests merged in 2025-04, with the labels that each got.

#7588 Add March 2025 CI incident blog post
  apps/site/pages/en/blog/vulnerability/march-2025-ci-incident.md
Labels: fast-track

#7465 feat(learn): organise TypeScript articles from simplest to advanced usage
  apps/site/navigation.json
  apps/site/pages/en/learn/typescript/run-natively.md
  apps/site/pages/en/learn/typescript/run.md
  apps/site/pages/en/learn/typescript/transpile.md
Labels: content, learn

#7609 fix(learn): fix typo in fetch learn
  apps/site/pages/en/learn/getting-started/fetch.md
Labels: fast-track

#7617 Revert "chore: refactor the `generateBlogData` function (#7607)"
  apps/site/next-data/generators/blogData.mjs
Labels: fast-track

#7627 chore: fix `getBreadrumbs` typo
  apps/site/components/withBreadcrumbs.tsx
Labels: fast-track

#7629 refactor: remove useless promise.all
  apps/site/next-data/generators/releaseData.mjs
Labels: fast-track

#7562 feat(about): list official resources
  apps/site/pages/en/about/index.mdx
Labels: content

#7641 fix(COLLABORATOR_GUIDE): remove `next-sitemap`
  COLLABORATOR_GUIDE.md
Labels: fast-track

#7639 feat(learn): add article on tuning memory
  apps/site/authors.json
  apps/site/pages/en/learn/diagnostics/memory/index.md
  apps/site/pages/en/learn/diagnostics/memory/understanding-and-tuning-memory.md
  apps/site/pages/en/learn/diagnostics/user-journey.md
  apps/site/pages/en/learn/test-runner/collecting-code-coverage.md
  packages/i18n/locales/en.json
Labels: learn

#7650 fix(download): Devbox is not supported on Windows
  apps/site/util/downloadUtils.tsx
Labels: fast-track

#7660 chore(test): use `t.mock.module` for mocking
  apps/site/package.json
  apps/site/tests/loader.mjs
  apps/site/tests/mocks/next-intl.jsx
  apps/site/tests/mocks/next-router.mjs
  apps/site/tests/setup.jsx
  apps/site/tests/setup.mjs
Labels: fast-track

#7661 fix(codecov): don't upload from merge queue
  .github/workflows/lint-and-tests.yml
Labels: fast-track

#7664 chore: correct sentence in TypeScript introduction
  apps/site/pages/en/learn/typescript/introduction.md
Labels: fast-track

#7645 feat(learn): add article on promises
  apps/site/navigation.json
  apps/site/pages/en/learn/asynchronous-work/discover-promises-in-nodejs.md
  packages/i18n/locales/en.json
Labels: content, learn

#7666 fix(chromatic): better job name
  .github/workflows/chromatic.yml
Labels: fast-track

#7667 fix(chromatic): run on merge
  .github/workflows/chromatic.yml
Labels: fast-track

#7665 fix(content): broken link in TypeScript runner
  apps/site/pages/en/learn/typescript/run.md
Labels: fast-track

#7670 Blog: v20.19.1 release post
  apps/site/pages/en/blog/release/v20.19.1.md
Labels: fast-track

#7671 fix(ci): use Github Bot for Crowdin
  .github/workflows/translations-sync.yml
Labels: fast-track

#7649 feat(select): scroll buttons
  apps/site/next.config.mjs
  package-lock.json
  packages/ui-components/Common/Select/index.module.css
  packages/ui-components/Common/Select/index.stories.tsx
  packages/ui-components/Common/Select/index.tsx
  packages/ui-components/package.json
Labels: design

#7685 chore: add banners
  apps/site/site.json
Labels: fast-track

#7684 docs: nvm references latest version
  apps/site/snippets/en/download/nvm.bash
Labels: fast-track

#7689 chore: update v18 EOL banner
  apps/site/site.json
Labels: fast-track
